version: 2
jobs:
  build:
    working_directory: ~/RxSwiftCommunity/RxCoreLocation
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      LANG: en_US.UTF-8
    macos:
      xcode: '9.4.0'
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - run:
        working_directory: ~/RxSwiftCommunity/RxCoreLocation
        command: xcodebuild -version
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-
        - v1-dep-
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - Carthage
    # Test
    - run: set -o pipefail
    - run: xcodebuild test -workspace RxCoreLocation.xcworkspace -scheme 'RxCoreLocation-iOS' -sdk iphonesimulator -destination "name=iPhone X" | xcpretty -c --test
    - run: xcodebuild build -workspace RxCoreLocation.xcworkspace -scheme RxCoreLocation-watchOS -sdk watchsimulator -destination "name=Apple Watch Series 2 - 42mm" | xcpretty -c
    - run: xcodebuild build -workspace RxCoreLocation.xcworkspace -scheme RxCoreLocation-macOS -sdk macosx -destination "arch=x86_64" | xcpretty -c
    - run: xcodebuild build -workspace RxCoreLocation.xcworkspace -scheme RxCoreLocation-tvOS -sdk appletvsimulator -destination "name=Apple TV 4K (at 1080p)" | xcpretty -c
    # Teardown
    - run: find $HOME/Library/Developer/Xcode/DerivedData -name '*.xcactivitylog' -exec cp {} $CIRCLE_ARTIFACTS/xcactivitylog \; || true
    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
